name: Firebase
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '10'

      - name: Check out code
        uses: actions/checkout@master

      - name: Install firebase
        run: yarn global add firebase-tools eslint

      - name: Install
        run: cd functions && yarn install

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only functions
